// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleVelocity.Common.Data;

#nullable disable

namespace VehicleVelocity.Common.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260311094755_UpdateVehicleModelAuditFields")]
    partial class UpdateVehicleModelAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleVelocity.Common.Models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<string>("AIAuditNotes")
                        .HasColumnType("text")
                        .HasColumnName("ai_audit_notes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("InspectionNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inspection_notes");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("LocationId")
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<bool>("NeedsManualReview")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_manual_review");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<int>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<string>("RiskReason")
                        .HasColumnType("text")
                        .HasColumnName("risk_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Vin")
                        .HasName("pk_vehicles");

                    b.ToTable("vehicles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
