// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleVelocity.Common.Data;

#nullable disable

namespace VehicleVelocity.Common.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260313104324_UpdateToAssistedAuditModel")]
    partial class UpdateToAssistedAuditModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleVelocity.Common.Models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<string>("AIAuditNotes")
                        .HasColumnType("text")
                        .HasColumnName("ai_audit_notes");

                    b.Property<string>("AuditRecommendation")
                        .HasColumnType("text")
                        .HasColumnName("audit_recommendation");

                    b.Property<int>("DeploymentPhase")
                        .HasColumnType("integer")
                        .HasColumnName("deployment_phase");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("InspectionNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inspection_notes");

                    b.Property<bool>("IsHighPriorityAudit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_high_priority_audit");

                    b.Property<bool>("IsLeadOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lead_override");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("LocationId")
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.Property<string>("Make")
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<bool>("NeedsManualReview")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_manual_review");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("override_reason");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<int>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("RiskReason")
                        .HasColumnType("text")
                        .HasColumnName("risk_reason");

                    b.Property<string>("ShadowAction")
                        .HasColumnType("text")
                        .HasColumnName("shadow_action");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Vin")
                        .HasName("pk_vehicles");

                    b.ToTable("vehicles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
